import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it, vi } from "vitest";

import { createDomainPersister } from "./domain-persistence";
import type { DomainArtifact, DomainCase } from "./domain-agent-runtime";

const sampleCase: DomainCase = {
  id: "case-1",
  subject: "Sangfor firewall opportunity",
  tags: ["firewall"],
};

const artifact: DomainArtifact = {
  produces: "sales-proposal",
  summary: "Draft generated by a domain pipeline.",
  payload: {
    structured: {
      customer: "Acme",
      opportunityTitle: "Acme firewall",
    },
  },
};

describe("createDomainPersister fail-closed boundary", () => {
  it.each(["marketing", "sales", "presales", "engineer", "cfo"] as const)(
    "returns a persisted human-review draft for %s without entity mutation",
    async (domain) => {
      const persistenceAuthority = new Proxy(
        {},
        {
          get: vi.fn(() => {
            throw new Error("database authority must not be read");
          }),
        },
      );
      const resolveProjectId = vi.fn(async () => "default-project");
      const persist = createDomainPersister({
        prisma: persistenceAuthority,
        resolveProjectId,
      });

      const result = await persist({
        domain,
        case: sampleCase,
        artifact,
        projectSlug: "caller-project",
      });

      expect(result).toEqual({
        domain,
        persisted: [
          {
            entity: "DomainArtifactReviewDraft",
            id: `domain-review:${domain}:case-1:sales-proposal`,
          },
        ],
        skipped: "authenticated_crm_context_required",
        reviewRequired: true,
        authenticatedApiPath: "/api/opportunities",
        quoteDraftPath: "/api/opportunities/[id]/quotes",
      });
      expect(resolveProjectId).not.toHaveBeenCalled();
    },
  );

  it("is deterministic for replay without synthesizing a scope", async () => {
    const persist = createDomainPersister();

    const first = await persist({
      domain: "sales",
      case: sampleCase,
      artifact,
    });
    const second = await persist({
      domain: "sales",
      case: sampleCase,
      artifact,
    });

    expect(second).toEqual(first);
  });

  it("contains no direct Customer, Opportunity, or Quote persistence authority", () => {
    const source = readFileSync(
      fileURLToPath(new URL("./domain-persistence.ts", import.meta.url)),
      "utf8",
    );

    expect(source).not.toMatch(/\.(?:customer|opportunity|quote|customerAsset|assetLicense|subscription)\.(?:create|update|upsert)/);
    expect(source).not.toMatch(/resolveDefaultProject|withRlsTransaction/);
    expect(source).not.toMatch(/createQuoteVersion/);
  });
});
