/**
 * U010 scope-inventory validator. Reads the live Prisma DMMF (via `Prisma.dmmf`, generated by
 * `prisma generate` — never text/regex over schema.prisma) and cross-checks it against
 * `packages/db/src/scope-inventory.ts`'s `MODEL_SCOPE_INVENTORY`: exact model-set match,
 * category tallies against `SCOPE_INVENTORY_BASELINE`, every CHILD_VIA_FK entry's recorded
 * parent/relationField/scalarFkField/nullable, structural ambiguous/dead-end chains, and the
 * Project<->Company scope-bridge `onDelete: Restrict` contract. Prints the JSON report to
 * stdout and exits 0 only when every check passes.
 */
import { Prisma } from '@prisma/client';

import {
  MODEL_SCOPE_INVENTORY,
  assertScopeBridgeOnDelete,
  buildScopeInventoryReport,
  deriveStructuralMismatches,
  validateChildViaFkEntries,
  type DmmfRelationField,
  type ScopeInventoryEntry,
} from '../src/scope-inventory';

function buildDmmfRelations(): DmmfRelationField[] {
  const models = Prisma.dmmf.datamodel.models;
  const relations: DmmfRelationField[] = [];
  for (const model of models) {
    for (const field of model.fields) {
      if (field.kind !== 'object' || !field.relationFromFields || field.relationFromFields.length === 0) {
        continue;
      }
      const scalarFkFields = [...field.relationFromFields];
      const mandatory =
        field.isRequired !== false &&
        scalarFkFields.every((fkName) => {
          const scalar = model.fields.find((f) => f.name === fkName);
          return scalar ? scalar.isRequired : false;
        });
      relations.push({
        model: model.name,
        relationField: field.name,
        targetModel: field.type,
        scalarFkFields,
        mandatory,
        onDelete: field.relationOnDelete ?? null,
      });
    }
  }
  return relations;
}

function findProjectCompanyRelation(dmmf: DmmfRelationField[]): DmmfRelationField | undefined {
  return dmmf.find((r) => r.model === 'Project' && r.relationField === 'company');
}

function main(): number {
  const models = Prisma.dmmf.datamodel.models;
  const currentModelNames = models.map((m) => m.name);
  const dmmfRelations = buildDmmfRelations();
  const entries: ScopeInventoryEntry[] = Object.values(MODEL_SCOPE_INVENTORY);

  const inventoryReport = buildScopeInventoryReport(currentModelNames, entries);
  const childFkErrors = validateChildViaFkEntries(entries, dmmfRelations);
  const structuralErrors = deriveStructuralMismatches(entries, dmmfRelations);

  const bridgeRelation = findProjectCompanyRelation(dmmfRelations);
  const bridgeCheck = assertScopeBridgeOnDelete(bridgeRelation?.onDelete ?? null);
  const bridgeErrors = bridgeRelation
    ? bridgeCheck.ok
      ? []
      : [{ code: 'SEMANTIC_MISMATCH' as const, message: bridgeCheck.reason ?? 'scope bridge onDelete invalid' }]
    : [{ code: 'SEMANTIC_MISMATCH' as const, message: 'Project.company relation not found in live schema' }];

  const allErrors = [...inventoryReport.errors, ...childFkErrors, ...structuralErrors, ...bridgeErrors];

  const report = {
    ok: allErrors.length === 0,
    baseSha: inventoryReport.baseSha,
    currentModelCount: inventoryReport.currentModelCount,
    inventoryModelCount: inventoryReport.inventoryModelCount,
    tallies: inventoryReport.tallies,
    baselineTallies: inventoryReport.baselineTallies,
    missingModels: inventoryReport.missingModels,
    unknownModels: inventoryReport.unknownModels,
    duplicateModels: inventoryReport.duplicateModels,
    scopeBridge: {
      onDelete: bridgeRelation?.onDelete ?? null,
      nullable: bridgeRelation ? !bridgeRelation.mandatory : null,
      ok: bridgeCheck.ok && Boolean(bridgeRelation),
    },
    errors: allErrors,
  };

  process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
  return report.ok ? 0 : 1;
}

process.exit(main());
